name: Publish

on:
  push:
    # tags:
    # - 'v*'

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run:
          pip install -r requirements.txt
      - name: build
        id: build
        run:
          sphinx-build -b html -d _build/doctrees . _build/html

      - uses: EndBug/add-and-commit@v7
        with:
          committer_name: GitHub Actions
          committer_email: actions@github.com