name: Tests

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ master ]

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: install
        run:
          pip install -r requirements.txt
      - name: nitpick
        id: nitpick
        run:
          sphinx-build -n source build
      - name: linkcheck
        id: linkcheck
        run:
          sphinx-build -M linkcheck source build || true
      - name: spelling
        id: spelling
        run:
          sphinx-build -b spelling source build/spelling

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: install
        run:
          pip install -r requirements.txt
      - name: build
        id: build
        run:
          sphinx-build -M html source build
